# Generated by Django 2.1 on 2018-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180930_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
