# Generated by Django 2.1 on 2018-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_app_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('password1', models.CharField(db_index=True, max_length=100)),
                ('password2', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
