# Generated by Django 2.1 on 2018-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181007_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_slug',
            field=models.SlugField(),
        ),
    ]
